-- Transit Survey Project Startup Form
-- Run this in a Snowflake worksheet (or snowsql) before starting the API.

CREATE DATABASE IF NOT EXISTS TRANSIT_SURVEY;
CREATE SCHEMA IF NOT EXISTS TRANSIT_SURVEY.STARTUP_FORM;

USE DATABASE TRANSIT_SURVEY;
USE SCHEMA STARTUP_FORM;

CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR(36) PRIMARY KEY,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    IS_ADMIN BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PROJECTS (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(500) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LANGUAGES (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PROJECT_SNAPSHOTS (
    ID VARCHAR(36) PRIMARY KEY,
    PROJECT_ID VARCHAR(36) NOT NULL,
    SAVED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SAVED_BY_USER_ID VARCHAR(36),
    SAVED_BY_NAME VARCHAR(255) NOT NULL,
    PROJECT_NAME VARCHAR(500),
    PROJECT_LIST_NAME VARCHAR(500),
    CLIENT_NAME VARCHAR(500),
    LOCATION_CITY_COUNTY VARCHAR(255),
    LOCATION_STATE VARCHAR(100),
    FIELD_START_DATE DATE,
    PROJECT_MANAGER_NAME VARCHAR(255),
    FIELD_SUPERVISOR_NAME VARCHAR(255),
    OD_INTERCEPT BOOLEAN,
    QUESTIONNAIRE_FILENAME VARCHAR(500),
    QUESTIONNAIRE_PATH VARCHAR(1000),
    SAMPLING_PLAN_FILENAME VARCHAR(500),
    SAMPLING_PLAN_PATH VARCHAR(1000),
    CALLBACK_LANGUAGES ARRAY,
    OD_TRANSLATION_LANGUAGES ARRAY,
    NON_DESTINATION_PLACE_TYPE BOOLEAN,
    EXTRA_TRIPS_SURVEY BOOLEAN,
    COMPANION_SURVEY BOOLEAN,
    TOUR_SURVEY BOOLEAN,
    OD_INTERCEPT_WEEKEND BOOLEAN,
    QUESTIONNAIRE_WEEKEND_FILENAME VARCHAR(500),
    QUESTIONNAIRE_WEEKEND_PATH VARCHAR(1000),
    SAMPLING_PLAN_WEEKEND_FILENAME VARCHAR(500),
    SAMPLING_PLAN_WEEKEND_PATH VARCHAR(1000),
    CALLBACK_LANGUAGES_WEEKEND ARRAY,
    OD_TRANSLATION_LANGUAGES_WEEKEND ARRAY,
    NON_DESTINATION_PLACE_TYPE_WEEKEND BOOLEAN,
    EXTRA_TRIPS_SURVEY_WEEKEND BOOLEAN,
    COMPANION_SURVEY_WEEKEND BOOLEAN,
    TOUR_SURVEY_WEEKEND BOOLEAN,
    SAS_SURVEY BOOLEAN,
    SAS_TRANSLATION_LANGUAGES ARRAY,
    ADDITIONAL_NOTES VARCHAR(16777216)
);

-- Seed language list (idempotent)
MERGE INTO LANGUAGES AS t
USING (
    SELECT column1 AS ID, column2 AS NAME FROM VALUES
        ('lang-spanish', 'Spanish'),
        ('lang-chinese', 'Chinese'),
        ('lang-vietnamese', 'Vietnamese'),
        ('lang-korean', 'Korean'),
        ('lang-tagalog', 'Tagalog'),
        ('lang-arabic', 'Arabic'),
        ('lang-french', 'French'),
        ('lang-haitian-creole', 'Haitian Creole'),
        ('lang-portuguese', 'Portuguese'),
        ('lang-russian', 'Russian'),
        ('lang-hindi', 'Hindi'),
        ('lang-polish', 'Polish')
) AS s
ON t.ID = s.ID
WHEN NOT MATCHED THEN
    INSERT (ID, NAME, IS_ACTIVE) VALUES (s.ID, s.NAME, TRUE);
