USE DATABASE TRANSIT_SURVEY;
USE SCHEMA STARTUP_FORM;

ALTER TABLE PROJECT_SNAPSHOTS ADD COLUMN IF NOT EXISTS OD_INTERCEPT_WEEKEND BOOLEAN;
ALTER TABLE PROJECT_SNAPSHOTS ADD COLUMN IF NOT EXISTS QUESTIONNAIRE_WEEKEND_FILENAME VARCHAR(500);
ALTER TABLE PROJECT_SNAPSHOTS ADD COLUMN IF NOT EXISTS QUESTIONNAIRE_WEEKEND_PATH VARCHAR(1000);
ALTER TABLE PROJECT_SNAPSHOTS ADD COLUMN IF NOT EXISTS SAMPLING_PLAN_WEEKEND_FILENAME VARCHAR(500);
ALTER TABLE PROJECT_SNAPSHOTS ADD COLUMN IF NOT EXISTS SAMPLING_PLAN_WEEKEND_PATH VARCHAR(1000);
ALTER TABLE PROJECT_SNAPSHOTS ADD COLUMN IF NOT EXISTS CALLBACK_LANGUAGES_WEEKEND ARRAY;
ALTER TABLE PROJECT_SNAPSHOTS ADD COLUMN IF NOT EXISTS OD_TRANSLATION_LANGUAGES_WEEKEND ARRAY;
ALTER TABLE PROJECT_SNAPSHOTS ADD COLUMN IF NOT EXISTS NON_DESTINATION_PLACE_TYPE_WEEKEND BOOLEAN;
ALTER TABLE PROJECT_SNAPSHOTS ADD COLUMN IF NOT EXISTS EXTRA_TRIPS_SURVEY_WEEKEND BOOLEAN;
ALTER TABLE PROJECT_SNAPSHOTS ADD COLUMN IF NOT EXISTS COMPANION_SURVEY_WEEKEND BOOLEAN;
